### ISSUE TITLE
load_project misses modules not reachable via imports

### ISSUE THREAD

**Issue by Mkerian10** [Mkerian10/pluto#211]
## Description

`load_project` only loads modules reachable by following imports or that have no compilation errors. Given a project with 9 source modules, only 1 appeared in `list_modules` after `load_project`, with the other 8 missing. The response showed `files_found: 18, files_loaded: 13, files_failed: 5`, but only 7 unique modules in `list_modules`. The missing modules compile fine individually via `load_module`.

## Expected Behavior

`load_project` should load ALL `.pluto` files in the directory tree, regardless of whether they're imported by other files or have compilation errors.

## Component

MCP server / CompilerService `load_project` method

**Comment by Mkerian10** [comment]
Fixed in commit 23c705d. load_project now uses standalone mode to compile each file independently, ensuring all .pluto files are loaded regardless of imports or dependencies.
